# Generated by Django 4.2.7 on 2026-05-19 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_stripe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='accounts_us_plan_05375f_idx',
            old_name='accounts_us_plan_8e0f0d_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='copy_generations_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_generations_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_period_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
