# Generated by Django 4.2.7 on 2026-05-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0004_generationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad_type', models.CharField(choices=[('copy', 'Copy'), ('image', 'Image')], default='copy', max_length=16)),
                ('content', models.TextField()),
                ('platform_format', models.CharField(choices=[('square', 'Square'), ('story', 'Story'), ('banner', 'Banner')], default='square', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('product_name', models.CharField(blank=True, default='', max_length=512)),
                ('style', models.CharField(blank=True, default='', max_length=128)),
                ('platform_format', models.CharField(choices=[('square', 'Square'), ('story', 'Story'), ('banner', 'Banner')], default='square', max_length=16)),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='generationrecord',
            new_name='studio_gene_user_id_ab4879_idx',
            old_name='studio_gen_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='generationrecord',
            new_name='studio_gene_source__a73ab5_idx',
            old_name='studio_gen_source_idx',
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_jobs', to='studio.adbrief'),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedad',
            name='brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ads', to='studio.adbrief'),
        ),
        migrations.AddField(
            model_name='generatedad',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ads', to='studio.campaign'),
        ),
        migrations.AddField(
            model_name='generatedad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
